# Generated by Django 3.0.8 on 2020-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0003_appt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Customer List',
            },
        ),
        migrations.CreateModel(
            name='TVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'TV',
            },
        ),
        migrations.AddField(
            model_name='appt',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
