# Generated by Django 3.0.8 on 2020-12-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0004_auto_20201128_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='apptDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
