# Generated by Django 3.0.8 on 2020-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0005_appt_apptdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='note',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
