# Generated by Django 3.0.8 on 2020-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0006_appt_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='calNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
