# Generated by Django 3.0.8 on 2020-12-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0010_appt_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='monthNum',
        ),
    ]
