# Generated by Django 3.0.8 on 2020-12-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0011_remove_appt_monthnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='cal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='scv.Calendar'),
        ),
    ]
