# Generated by Django 3.0.8 on 2020-12-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0012_auto_20201204_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='cal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='scv.Calendar'),
        ),
    ]
