# Generated by Django 3.0.8 on 2020-12-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0013_auto_20201204_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='cal',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
