# Generated by Django 3.0.8 on 2020-12-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0014_auto_20201207_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='diagnosedBol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appt',
            name='finishBol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appt',
            name='partsBol',
            field=models.BooleanField(default=False),
        ),
    ]
