# Generated by Django 3.0.8 on 2020-12-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0016_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='appt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='scv.Appt'),
        ),
    ]
