# Generated by Django 3.0.8 on 2020-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0018_appt_partc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='partC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
