# Generated by Django 3.0.8 on 2020-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0020_auto_20201213_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
