# Generated by Django 3.0.8 on 2020-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0021_testm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestM',
        ),
        migrations.AddField(
            model_name='appt',
            name='issus',
            field=models.CharField(default='Other', max_length=255),
            preserve_default=False,
        ),
    ]
