# Generated by Django 3.0.8 on 2020-12-20 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0022_auto_20201216_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='scv.User'),
        ),
    ]
