# Generated by Django 3.0.8 on 2021-01-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0023_appt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='apptDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
