# Generated by Django 3.0.8 on 2021-01-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0024_auto_20210101_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='monthNum',
            field=models.ImageField(blank=True, default=1, null=True, upload_to=''),
        ),
    ]
