# Generated by Django 3.0.8 on 2021-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0025_appt_monthnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='monthNum',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
