# Generated by Django 3.0.8 on 2021-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0026_auto_20210103_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='monthNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
